#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Sensor, dgtl3,  ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int go = 0;
task main()
{
	while(1){
		if(SensorValue(port3) == 1){
			if(go == 1){
				go = 0;
				StopMotor(port2);
			}
			else{
				go = 1
				startMotor(port2, 125); //More then one speed later?
		}
		}
	}


}
